# apt
- src: https://github.com/vterdunov/ansible-apt
  name: apt

# ruby-brightbox
- src: https://github.com/vterdunov/ansible-ruby-brightbox
  name: ruby-brightbox

# mysql
- src: https://github.com/ANXS/mysql
  name: mysql
